name: colorization-pytorch
channels:
- defaults
dependencies:
  - python=3.6.8
  - pytorch=0.4.1
  - torchvision
  - scipy
  - wget
  - IPython
  - pip

  - pip:
    - dominate==2.3.1
    - Pillow==5.0.0
    - numpy
    - visdom==0.1.7
    - parso==0.7.0