name: colorization-pytorch
channels:
- defaults
dependencies:
  - python=3.5.5
  - pytorch=0.4.1
  - torchvision
  - scipy
  - pip

  - pip:
    - dominate==2.3.1
    - Pillow==5.0.0
    - numpy==1.14.1
    - visdom==0.1.7